# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Expose port 8000 for the web server
EXPOSE 8000

# Start the Python HTTP server
CMD ["python", "-m", "http.server", "8000"]

